import './globals.css';
import './partition.css';
import './toolbar.css';
import './slider.css';
import './header.css';
import './characterSelector.css';
import './characterSettings.css';
import './skillsModal.css';
import './splitGutter.css';
import './animations.css';
import './damageSection.css';
import './inherentSkills.css';
import './reset.css';
import './customBuffs.css';
import './checkbox.css';
import './resetMenu.css'
import './changeLogModal.css';
import './dropdownSelect.css';
import './info.css';